version: "3"

services:

 app: 
  build:
   context: node
  container_name: app
  volumes:
   - ./node:/usr/src/app
  entrypoint: sh -c "npm install && node index.js"
  tty: true
  networks:
   - desafionet
  depends_on:
   db:
    condition: service_healthy    

 nginx:
  image: nginx:1.15.0-alpine
  container_name: nginx
  ports:
   - "8080:8080"
  depends_on:
      - app
  volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  networks:
   - desafionet   

 db:
  platform: linux/x86_64
  image: mysql:5.7
  command: --innodb-use-native-aio=0
  container_name: db
  restart: always
  tty: true
  volumes:
   - "./schema.sql:/docker-entrypoint-initdb.d/1.sql"
   - ./mysql:/var/lib/mysql
  environment:
   - MYSQL_DATABASE=nodedb
   - MYSQL_ROOT_PASSWORD=root
  healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3
  networks:
   - desafionet


networks:
 desafionet:
  driver: bridge

